name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Add workflow-level permissions
permissions:
  contents: read
  packages: write

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: dela-builder
  PLATFORM: linux/amd64
  CACHE_KEY: dela-builder-cache

jobs:
  build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Cache Docker layers
      - name: Set up Docker layer caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.CACHE_KEY }}-${{ hashFiles('Cargo.lock', 'tests/Dockerfile.builder') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ env.CACHE_KEY }}-

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: tests/Dockerfile.builder
          platforms: ${{ env.PLATFORM }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Move cache to prevent it from growing indefinitely
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  shell-tests:
    name: Shell Tests
    needs: build-base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [unit, noinit, zsh, bash, fish, pwsh]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ${{ matrix.shell }} tests
        env:
          VERBOSE: 1
          DOCKER_PLATFORM: ${{ env.PLATFORM }}
          BUILDER_IMAGE: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        run: ./tests/run_tests.sh ${{ matrix.shell }} 