name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: tests/Dockerfile.builder
          tags: dela-builder:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix for https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  shell-tests:
    name: Shell Tests
    needs: build-base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [zsh, bash, fish, pwsh]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: tests/Dockerfile.builder
          tags: dela-builder:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Run ${{ matrix.shell }} tests
        run: VERBOSE=1 ./tests/run_tests.sh ${{ matrix.shell }} 