name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:
    inputs:
      skip_github_release:
        description: 'Skip GitHub release creation'
        type: boolean
        default: false
      skip_binary_build:
        description: 'Skip binary builds'
        type: boolean
        default: false
      skip_crates_publish:
        description: 'Skip publishing to crates.io'
        type: boolean
        default: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    if: ${{ !inputs.skip_github_release }}
    steps:
      - uses: actions/checkout@v4
      
      # Check if release already exists
      - name: Check existing release
        id: check_release
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          if gh release view "$TAG_NAME" &> /dev/null; then
            echo "Release already exists"
            UPLOAD_URL=$(gh release view "$TAG_NAME" --json uploadUrl -q .uploadUrl)
            echo "upload_url=$UPLOAD_URL" >> $GITHUB_OUTPUT
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        if: steps.check_release.outputs.exists != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-release:
    name: Build Release
    needs: create-release
    if: ${{ !inputs.skip_binary_build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
            archive_name: dela-linux-amd64.tar.gz
          - build: linux-arm64
            os: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-gnu
            archive_name: dela-linux-arm64.tar.gz
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            archive_name: dela-darwin-amd64.tar.gz
          - build: macos-arm64
            os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
            archive_name: dela-darwin-arm64.tar.gz
          - build: windows
            os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
            archive_name: dela-windows-amd64.zip
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install Cross-Compilation Tools
      if: matrix.build == 'linux-arm64'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Build Binary
      run: |
        cargo build --release --target ${{ matrix.target }}

    - name: Prepare Archive (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        tar czvf ../../../${{ matrix.archive_name }} dela
        cd -

    - name: Prepare Archive (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        7z a ../../../${{ matrix.archive_name }} dela.exe
        cd -

    # Check if asset already exists
    - name: Check existing asset
      id: check_asset
      run: |
        TAG_NAME="${GITHUB_REF#refs/tags/}"
        if gh release view "$TAG_NAME" --json assets -q ".assets[].name" | grep -q "^${{ matrix.archive_name }}$"; then
          echo "Asset already exists"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: steps.check_asset.outputs.exists != 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./${{ matrix.archive_name }}
        asset_name: ${{ matrix.archive_name }}
        asset_content_type: application/octet-stream

  publish-crate:
    name: Publish to crates.io
    needs: [create-release, build-release]
    if: ${{ !inputs.skip_crates_publish }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Check if version is already published
      - name: Check if version exists on crates.io
        id: check_version
        run: |
          VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          if cargo search dela --limit 1 | grep -q "dela = \"$VERSION\""; then
            echo "Version $VERSION already exists on crates.io"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Check package
        if: steps.check_version.outputs.exists != 'true'
        run: cargo package --locked

      - name: Publish to crates.io
        if: steps.check_version.outputs.exists != 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --locked 